import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';

const origin = process.env.PREVIEW_URL || 'http://127.0.0.1:4175';
const captures = await fs.mkdtemp(path.join(os.tmpdir(), 'whrds-charcoal-qa-'));
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const report = { captures, checks: [], errors: [] };
const check = (name, value) => { assert.ok(value, name); report.checks.push(name); };
const fit = page => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth);
async function screenshot(page, name) { await page.screenshot({ path: path.join(captures, name + '.png') }); }
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, deviceScaleFactor: 1, reducedMotion: 'reduce', colorScheme: 'light' });
  page.on('pageerror', error => report.errors.push(error.message));
  await page.goto(origin + '/ko/', { waitUntil: 'networkidle' });
  await page.waitForSelector('[data-hardware][data-state="ready"]', { timeout: 90000 });
  check('new visitors get charcoal even with a light OS preference', await page.locator('html').getAttribute('data-theme') === 'dark');
  check('mobile browser chrome matches charcoal', await page.locator('meta[name="theme-color"]').getAttribute('content') === '#101215');
  check('all 79 entries remain', await page.locator('.post-card').count() === 79);
  check('all five profile achievements remain', await page.locator('.profile-card li').count() === 5);
  check('archive counts match content', (await page.locator('.archive-ledger').textContent()).includes('79') && (await page.locator('.archive-ledger').textContent()).includes('08'));
  await screenshot(page, 'home-dark');
  await page.locator('#notes').scrollIntoViewIfNeeded();
  await screenshot(page, 'notes-profile-dark');
  const article = await page.locator('.post-card h3 a').first().getAttribute('href');
  const contrast = await page.locator('.post-card p').first().evaluate(el => {
    const rgb = value => value.match(/[\d.]+/g).slice(0, 3).map(Number);
    const lum = values => values.map(v => { v /= 255; return v <= .04045 ? v / 12.92 : ((v + .055) / 1.055) ** 2.4; }).reduce((a, v, i) => a + v * [.2126, .7152, .0722][i], 0);
    const color = lum(rgb(getComputedStyle(el).color));
    const surface = getComputedStyle(document.documentElement).getPropertyValue('--panel-top').trim();
    const values = surface.slice(1).match(/../g).map(v => parseInt(v, 16));
    const background = lum(values); return (Math.max(color, background) + .05) / (Math.min(color, background) + .05);
  });
  report.mutedTextContrast = contrast;
  check('muted article text meets 4.5:1 contrast', contrast >= 4.5);
  await page.goto(origin + '/ko/categories/');
  check('eight category links remain', await page.locator('.category-card').count() === 8);
  await screenshot(page, 'categories-dark');
  await page.locator('.category-card').first().click();
  check('category navigation works', await page.locator('.post-card').count() > 0);
  check('category title stays within the viewport', await fit(page));
  await page.goto(origin + article);
  check('article has readable content and no 3D bundle', await page.locator('.prose').isVisible() && await page.evaluate(() => !performance.getEntriesByType('resource').some(r => r.name.includes('hero3d.js'))));
  await screenshot(page, 'article-dark');
  await page.locator('.language-switch a[lang="en"]').click();
  check('article translation switch works', await page.locator('html').getAttribute('lang') === 'en' && await page.locator('.prose').isVisible());
  await page.goto(origin + '/ko/about/'); await screenshot(page, 'about-dark');
  await page.locator('[data-theme-toggle]').click();
  await page.goto(origin + '/ko/');
  await page.waitForSelector('[data-hardware][data-state="ready"]', { timeout: 90000 });
  check('explicit light preference persists between pages', await page.locator('html').getAttribute('data-theme') === 'light');
  await screenshot(page, 'home-light');
  await page.locator('[data-theme-toggle]').click();
  await page.locator('.language-switch a[lang="en"]').click();
  await page.waitForSelector('[data-hardware][data-state="ready"]', { timeout: 90000 });
  check('English home stays dark and fits', await page.locator('html').getAttribute('data-theme') === 'dark' && await fit(page));
  await screenshot(page, 'home-en');
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true, reducedMotion: 'reduce' });
  mobile.on('pageerror', error => report.errors.push(error.message));
  await mobile.goto(origin + '/ko/');
  await mobile.waitForSelector('[data-hardware][data-state="ready"]', { timeout: 90000 });
  check('mobile homepage fits', await fit(mobile));
  check('mobile main navigation is available', await mobile.locator('.main-nav').isVisible());
  await screenshot(mobile, 'mobile-home');
  await mobile.locator('[data-model-picker]').scrollIntoViewIfNeeded(); await screenshot(mobile, 'mobile-models');
  await mobile.locator('.main-nav a').nth(1).click();
  check('mobile category navigation works and fits', await mobile.locator('.category-card').count() === 8 && await fit(mobile));
  await screenshot(mobile, 'mobile-categories');
  await mobile.goto(origin + article); check('mobile article fits', await fit(mobile)); await screenshot(mobile, 'mobile-article');
  await mobile.setViewportSize({ width: 320, height: 740 });
  await mobile.goto(origin + '/en/');
  await mobile.waitForSelector('[data-hardware][data-state="ready"]', { timeout: 90000 });
  check('small 320px English viewport fits', await fit(mobile));
  await mobile.locator('[data-model-picker]').scrollIntoViewIfNeeded(); await screenshot(mobile, 'small-en');
  check('no JavaScript exceptions', report.errors.length === 0);
  console.log(JSON.stringify(report, null, 2));
} finally { await browser.close(); }
