import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import os from 'node:os';

const root = path.resolve(import.meta.dirname, '..');
const origin = process.env.PREVIEW_URL || 'http://127.0.0.1:4175';
const capturePoster = process.argv.includes('--poster');
const captureDir = await fs.mkdtemp(path.join(os.tmpdir(), 'whrds-three-qa-'));
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const report = { captures: captureDir, errors: [], checks: [] };
const check = (name, value) => { assert.ok(value, name); report.checks.push(name); };
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1050 }, deviceScaleFactor: 1, reducedMotion: 'reduce' });
  page.on('pageerror', (error) => report.errors.push(error.message));
  await page.addInitScript(() => { localStorage.setItem('theme', 'light'); });
  await page.goto(origin + '/ko/', { waitUntil: 'networkidle' });
  await page.waitForSelector('[data-hardware][data-state="ready"]', { timeout: 90000 });
  await page.waitForTimeout(800);
  check('reduced motion disables auto-rotation', await page.locator('[data-motion]').getAttribute('aria-pressed') === 'false');
  check('Korean headline preserved', (await page.locator('h1').textContent()) === '끄저끄적 작성 중...');
  check('all posts preserved', await page.locator('.post-card').count() === 79);
  report.renderer = await page.locator('[data-hardware]').evaluate((el) => ({ drawCalls: el.dataset.renderCalls, triangles: el.dataset.triangles, canvas: [el.querySelector('canvas').width, el.querySelector('canvas').height] }));
  await page.screenshot({ path: path.join(captureDir, 'desktop.png') });
  const assembledImage = await page.locator('[data-three-stage]').screenshot();
  if (capturePoster) {
    await page.addStyleTag({ content: '.hardware-overline,.hardware-side-label{visibility:hidden!important}' });
    await page.locator('[data-three-stage]').screenshot({ path: path.join(root, 'static/hardware-poster.png') });
    await page.locator('style').last().evaluate((el) => el.remove());
    check('poster generated from actual 3D model', true);
  }
  await page.locator('[data-explode]').click();
  await page.waitForTimeout(200);
  check('exploded view toggles', await page.locator('[data-explode]').getAttribute('aria-pressed') === 'true');
  check('exploded view changes actual rendered model', !assembledImage.equals(await page.locator('[data-three-stage]').screenshot()));
  await page.screenshot({ path: path.join(captureDir, 'exploded.png') });
  await page.locator('[data-reset]').click();
  check('reset assembles model', await page.locator('[data-explode]').getAttribute('aria-pressed') === 'false');
  const canvasBounds = await page.locator('[data-three-stage] canvas').boundingBox();
  const startFrames = Number(await page.locator('[data-hardware]').getAttribute('data-frames'));
  await page.mouse.move(canvasBounds.x + canvasBounds.width / 2, canvasBounds.y + canvasBounds.height / 2);
  await page.mouse.down(); await page.mouse.move(canvasBounds.x + canvasBounds.width / 2 + 65, canvasBounds.y + canvasBounds.height / 2 + 25, { steps: 8 }); await page.mouse.up();
  check('desktop drag triggers rendering', Number(await page.locator('[data-hardware]').getAttribute('data-frames')) > startFrames);
  await page.locator('[data-motion]').click();
  const activeFrames = Number(await page.locator('[data-hardware]').getAttribute('data-frames'));
  await page.waitForTimeout(500);
  check('explicit auto-rotate animates even when reduced motion is preferred', Number(await page.locator('[data-hardware]').getAttribute('data-frames')) > activeFrames + 2);
  await page.locator('.post-card').nth(5).scrollIntoViewIfNeeded();
  await page.waitForTimeout(400);
  const offscreenFrames = await page.locator('[data-hardware]').getAttribute('data-frames');
  await page.waitForTimeout(400);
  check('offscreen rendering pauses', await page.locator('[data-hardware]').getAttribute('data-frames') === offscreenFrames);
  await page.locator('[data-reset]').click();
  await page.locator('[data-theme-toggle]').click();
  check('dark theme still works', await page.locator('html').getAttribute('data-theme') === 'dark');
  await page.evaluate(() => scrollTo(0, 0));
  await page.waitForTimeout(250);
  const alpha = await page.locator('[data-three-stage] canvas').evaluate((canvas) => {
    const gl = canvas.getContext('webgl2'); const pixel = new Uint8Array(4);
    gl.readPixels(Math.floor(canvas.width / 2), Math.floor(canvas.height / 2), 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, pixel);
    return pixel[3];
  });
  check('idle canvas retains model after theme change and scroll return', alpha > 0);
  await page.screenshot({ path: path.join(captureDir, 'dark.png') });
  await page.locator('.language-switch a[lang="en"]').click();
  await page.waitForSelector('[data-state="ready"]', { timeout: 90000 });
  check('English controls translated', await page.locator('[data-explode]').textContent() === 'Explode');
  await page.goto(origin + '/ko/categories/');
  check('category pages intact', await page.locator('.category-card').count() === 8);
  check('3D bundle absent on category pages', await page.evaluate(() => !performance.getEntriesByType('resource').some((r) => r.name.includes('hero3d.js'))));
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true, reducedMotion: 'reduce' });
  mobile.on('pageerror', (error) => report.errors.push(error.message));
  await mobile.goto(origin + '/ko/', { waitUntil: 'networkidle' });
  await mobile.waitForSelector('[data-state="ready"]', { timeout: 90000 });
  check('mobile has no horizontal overflow', await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await mobile.screenshot({ path: path.join(captureDir, 'mobile.png') });
  await mobile.locator('[data-explode]').click();
  check('mobile explode button works', await mobile.locator('[data-explode]').getAttribute('aria-pressed') === 'true');
  const fallback = await browser.newPage({ viewport: { width: 900, height: 900 } });
  await fallback.addInitScript(() => {
    const original = HTMLCanvasElement.prototype.getContext;
    HTMLCanvasElement.prototype.getContext = function (type, ...args) { return type.startsWith('webgl') ? null : original.call(this, type, ...args); };
  });
  await fallback.goto(origin + '/ko/');
  await fallback.waitForSelector('[data-state="fallback"]');
  check('WebGL failure preserves posts', await fallback.locator('.post-card').count() === 79);
  if (!capturePoster) check('fallback poster loads', await fallback.locator('.hardware-poster').evaluate((img) => img.complete && img.naturalWidth > 0));
  const saver = await browser.newPage();
  await saver.addInitScript(() => { Object.defineProperty(navigator, 'connection', { value: { saveData: true } }); });
  await saver.goto(origin + '/ko/', { waitUntil: 'networkidle' });
  check('data saver does not download 3D automatically', await saver.evaluate(() => !performance.getEntriesByType('resource').some((r) => r.name.includes('hero3d.js'))));
  await saver.locator('[data-load-three]').click();
  await saver.waitForSelector('[data-state="ready"]', { timeout: 90000 });
  check('data saver allows explicit 3D opt-in', true);
  check('no JavaScript exceptions', report.errors.length === 0);
  console.log(JSON.stringify(report, null, 2));
} finally { await browser.close(); }
