import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';

const origin = process.env.PREVIEW_URL || 'http://127.0.0.1:4175';
const captures = await fs.mkdtemp(path.join(os.tmpdir(), 'whrds-mascot-qa-'));
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const report = { captures, checks: [], errors: [] };
const check = (name, value) => { assert.ok(value, name); report.checks.push(name); };
const transform = page => page.locator('.mascot-art').evaluate(el => getComputedStyle(el).transform);
const fit = page => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth);
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, reducedMotion: 'no-preference' });
  page.on('pageerror', error => report.errors.push(error.message));
  await page.goto(origin + '/ko/about/', { waitUntil: 'networkidle' });
  await page.waitForSelector('[data-mascot][data-animate="on"]');
  const body = await page.locator('.prose').textContent();
  check('Korean introduction includes research and all writing approaches', body.includes('시스템 해킹과 IoT 보안') && body.includes('직접 작성하는 방식') && body.includes('전적으로 활용'));
  check('mascot image loads with transparency', await page.locator('.mascot-art').evaluate(img => {
    const canvas = document.createElement('canvas'); canvas.width = canvas.height = 384;
    const ctx = canvas.getContext('2d'); ctx.drawImage(img, 0, 0);
    return img.complete && img.naturalWidth === 384 && ctx.getImageData(0, 0, 1, 1).data[3] === 0;
  }));
  const moving = await transform(page); await page.waitForTimeout(650);
  check('mascot actually moves', moving !== await transform(page));
  await page.locator('[data-mascot-toggle]').click();
  await page.locator('.mascot-art').evaluate(async el => { await Promise.all(el.getAnimations().map(animation => animation.ready)); });
  check('pause settles on the compositor', await page.locator('.mascot-art').evaluate(el => el.getAnimations().every(animation => animation.playState === 'paused')));
  const stopped = await transform(page); await page.waitForTimeout(400);
  check('pause button freezes the animation', stopped === await transform(page));
  await page.screenshot({ path: path.join(captures, 'about-ko.png'), fullPage: true });
  await page.locator('.language-switch a[lang="en"]').click();
  check('English introduction reflects AI-generated writing', (await page.locator('.prose').textContent()).includes('fully AI-generated posts'));
  check('pause preference persists across languages', await page.locator('[data-mascot]').getAttribute('data-animate') === 'off');
  await page.locator('[data-mascot-toggle]').focus(); await page.keyboard.press('Space');
  await page.waitForSelector('[data-animate="on"]');
  check('keyboard can resume animation', true);
  await page.screenshot({ path: path.join(captures, 'about-en.png'), fullPage: true });
  await page.goto(origin + '/ko/', { waitUntil: 'networkidle' });
  check('profile retains all achievements and posts', await page.locator('.profile-card li').count() === 5 && await page.locator('.post-card').count() === 79);
  check('offscreen mascot is paused', await page.locator('[data-mascot]').getAttribute('data-animate') === 'off');
  await page.locator('.profile-card').scrollIntoViewIfNeeded();
  await page.waitForSelector('[data-animate="on"]');
  check('profile mascot resumes when visible', true);
  await page.locator('[data-mascot-toggle]').click();
  await page.screenshot({ path: path.join(captures, 'profile.png') });
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce' });
  mobile.on('pageerror', error => report.errors.push(error.message));
  await mobile.goto(origin + '/ko/about/', { waitUntil: 'networkidle' });
  check('reduced motion defaults to a still mascot', await mobile.locator('[data-mascot]').getAttribute('data-animate') === 'off');
  const reducedPose = await transform(mobile); await mobile.waitForTimeout(350);
  check('reduced motion has no movement', reducedPose === await transform(mobile));
  check('mobile about layout fits', await fit(mobile));
  await mobile.screenshot({ path: path.join(captures, 'mobile-about.png'), fullPage: true });
  await mobile.locator('[data-mascot-toggle]').tap();
  await mobile.waitForSelector('[data-animate="on"]');
  const explicitPose = await transform(mobile); await mobile.waitForTimeout(350);
  check('mobile can explicitly enable motion', explicitPose !== await transform(mobile));
  await mobile.setViewportSize({ width: 320, height: 740 });
  await mobile.goto(origin + '/en/about/');
  check('small English about layout fits', await fit(mobile));
  await mobile.screenshot({ path: path.join(captures, 'small-about-en.png'), fullPage: true });
  await mobile.locator('[data-theme-toggle]').click();
  check('light theme remains available', await mobile.locator('html').getAttribute('data-theme') === 'light');
  await mobile.screenshot({ path: path.join(captures, 'light-about.png'), fullPage: true });
  check('no JavaScript errors', report.errors.length === 0);
  console.log(JSON.stringify(report, null, 2));
} finally { await browser.close(); }
